<?php
/**
 * Joomla! entity library.
 *
 * @copyright  Copyright (C) 2017-2019 Roberto Segura López, Inc. All rights reserved.
 * @license    See COPYING.txt
 */

namespace Phproberto\Joomla\Entity\Traits;

defined('_JEXEC') || die;

use Joomla\CMS\Application\CMSApplication;

/**
 * For classes having messages.
 *
 * @since  __DEPLOY_VERSION__
 */
trait HasMessages
{
	/**
	 * System messages for the user.
	 *
	 * @var   array
	 */
	protected $messages = [];

	/**
	 * Adds a system message.
	 *
	 * @param   string  $message  Message to show
	 * @param   string  $type     Type of message
	 *
	 * @return  self.
	 */
	protected function addMessage($message, $type = 'message')
	{
		if (!isset($this->messages[$type]))
		{
			$this->messages[$type] = array();
		}

		$this->messages[$type][] = $message;

		return $this;
	}

	/**
	 * Inject any pending message into the Joomla app.
	 *
	 * @param   CMSApplication  $app  Application to inject the messages
	 *
	 * @return  self
	 */
	protected function enqueueMessagesInApp(CMSApplication $app)
	{
		$systemMessages = $this->getMessages();

		if (!$systemMessages)
		{
			return $this;
		}

		foreach ($systemMessages as $messageType => $messages)
		{
			foreach ($messages as $message)
			{
				$app->enqueueMessage($message, $messageType);
			}
		}

		return $this;
	}

	/**
	 * Get the system messages generated by this view.
	 *
	 * @param   string  $type  Optional type selector
	 *
	 * @return  array
	 */
	public function getMessages($type = null)
	{
		return $type && isset($this->messages[$type]) ? $this->messages[$type] : $this->messages;
	}
}
