CREATE TABLE `jos_fields` (
	`id` INTEGER PRIMARY KEY NOT NULL,
	`asset_id` INTEGER NOT NULL DEFAULT '0',
	`context` TEXT NOT NULL DEFAULT '',
	`group_id` INTEGER NOT NULL DEFAULT '0',
	`title` TEXT NOT NULL DEFAULT '',
	`name` TEXT NOT NULL DEFAULT '',
	`label` TEXT NOT NULL DEFAULT '',
	`default_value` TEXT NOT NULL,
	`type` TEXT NOT NULL DEFAULT 'text',
	`note` TEXT NOT NULL DEFAULT '',
	`description` TEXT NOT NULL,
	`state` INTEGER NOT NULL DEFAULT '0',
	`required` INTEGER NOT NULL DEFAULT '0',
	`checked_out` INTEGER NOT NULL DEFAULT '0',
	`checked_out_time` TEXT NOT NULL DEFAULT '0000-00-00 00:00:00',
	`ordering` INTEGER NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	`fieldparams` TEXT NOT NULL,
	`language` TEXT NOT NULL DEFAULT '',
	`created_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_user_id` INTEGER NOT NULL DEFAULT '0',
	`modified_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` INTEGER NOT NULL DEFAULT '0',
	`access` INTEGER NOT NULL DEFAULT '1'
)