CREATE TABLE IF NOT EXISTS `jos_fields_groups` (
	`id` INTEGER PRIMARY KEY NOT NULL,
	`asset_id` INTEGER NOT NULL DEFAULT '0',
	`context` TEXT NOT NULL DEFAULT '',
	`title` TEXT NOT NULL DEFAULT '',
	`note` TEXT NOT NULL DEFAULT '',
	`description` TEXT NOT NULL,
	`state` INTEGER NOT NULL DEFAULT '0',
	`checked_out` INTEGER NOT NULL DEFAULT '0',
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`ordering` INTEGER NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	`language` TEXT NOT NULL DEFAULT '',
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` INTEGER NOT NULL DEFAULT '0',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` INTEGER NOT NULL DEFAULT '0',
	`access` INTEGER NOT NULL DEFAULT '1'
)
